# Site settings
title:       Willem Fletcher
author:      Willem Fletcher
baseurl:     ""
url:         "https://fletcherwill.github.io/"
notesurl: /assets/notes/
figuresurl: /assets/figures/

header_pages:
  - index.md
  - publications.md

keywords: ['Willem Fletcher', 'Will Fletcher', 'CS', 'computer science', 'Brown University']

# account settings
google_scholar: JR_KR7MAAAAJ
# arxiv_identifier: wang_a_3
# google_analytics: UA-145353243-1

# katex
katex:
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000" 
    delimiters: [
              {left: "$$", right: "$$", display: true},
            {left: "$", right: "$", display: false}]

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'strikethrough']
permalink:    pretty
sass:
  style: compressed
  sass_dir: ./_sass
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-paginate
  - jekyll-katex
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - CNAME


